version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: nextskill
      POSTGRES_USER: nextskill
      POSTGRES_PASSWORD: nextskill
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextskill"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pg_data:
